### ISSUE TITLE
failed to load bloom-filter module after npm installation

### ISSUE THREAD

**Issue by yanshoutong** [Callidon/bloom-filters#15]
```sh
$ npm install --save bloom-filters
$ node
Welcome to Node.js v12.12.0.
Type ".help" for more information.
> const { BloomFilter } = require('bloom-filters')
Thrown:
Error: Cannot find module '/Users/henry/tmp/bloom/node_modules/bloom-filters/bloom-filters.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:294:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:525:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:781:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/henry/tmp/bloom/node_modules/bloom-filters/package.json',
  requestPath: 'bloom-filters'
}
```

but if I use the version 0.8.0 , it works well.

**Comment by Callidon** [comment]
Hi,

Well, we forgot to update the `main` entry of the `package.json` file before releasing the version. I've just pushed a new version (`v1.0.3`) on npm that should fix this.

Could you please try again with the new version and report if the issue if fixed?

**Comment by yanshoutong** [comment]
many thanks for quick fix :)
